- Assets/Scenes/FelipeScene.unity
- Assets/Scenes/FelipeScene.unity.meta
> NewSceneFeli

- Assets/Scenes/ChinoScene.unity
- Assets/Scripts/Player/Controller.cs
- Assets/Scripts/Player/Model.cs
- ProjectSettings/BurstAotSettings_Android.json
- ProjectSettings/CommonBurstAotSettings.json
Aplique un sistema que pueda realizar 3 golpes
> Sistema de golpes

- Assets/Scenes/MatiScene.unity
- Assets/Scripts/Camera/CameraTracker.cs
- Assets/Scripts/Interface/Characters.cs
- Assets/Scripts/Interface/Characters.cs.meta
- Assets/Scripts/Interface/Entity.cs
- Assets/Scripts/Managers/GameManager.cs
- Assets/Scripts/Players.meta
- Assets/Scripts/Players/Banana.meta
- Assets/Scripts/Players/Banana/ControllerBanana.cs
- Assets/Scripts/Players/Banana/ControllerBanana.cs.meta
- Assets/Scripts/Players/Banana/ModelBanana.cs
- Assets/Scripts/Players/Banana/ModelBanana.cs.meta
- Assets/Scripts/Players/Banana/ViewBanana.cs
- Assets/Scripts/Players/Banana/ViewBanana.cs.meta
- Assets/Scripts/Players/Monkey.meta
- Assets/Scripts/Players/Monkey/ControllerMonkey.cs
- Assets/Scripts/Players/Monkey/ControllerMonkey.cs.meta
- Assets/Scripts/Players/Monkey/ModelMonkey.cs
- Assets/Scripts/Players/Monkey/ModelMonkey.cs.meta
- Assets/Scripts/Players/Monkey/Punch.cs
- Assets/Scripts/Players/Monkey/Punch.cs.meta
- Assets/Scripts/Players/Monkey/PunchSystemPlayer.cs
- Assets/Scripts/Players/Monkey/PunchSystemPlayer.cs.meta
- Assets/Scripts/Players/Monkey/ViewMonkey.cs
- Assets/Scripts/Players/Monkey/ViewMonkey.cs.meta
> Lo que hicimos en clase 09/04

- Assets/Prefabs/Enemy.prefab
- Assets/Scenes/MatiScene.unity
- Assets/Scripts/Enemy/Attack.cs
- Assets/Scripts/Enemy/Attack.cs.meta
- Assets/Scripts/Enemy/Enemy.cs
- Assets/Scripts/Enemy/Object Pool/InstantiateEnemies.cs
falta arreglar el cambio de estado con el fsm
> ataque del enemigo incompleto

- Assets/Material/M_Hook.mat
- Assets/Material/M_Hook.mat.meta
- Assets/Material/M_HookGun.mat
- Assets/Material/M_HookGun.mat.meta
- Assets/Scenes/ChinoScene.unity
- Assets/Scripts/Liana.cs
- Assets/Scripts/Liana.cs.meta
- Assets/Scripts/Players/Monkey/ControllerMonkey.cs
- Assets/Scripts/Players/Monkey/Hook.cs
- Assets/Scripts/Players/Monkey/ModelMonkey.cs
Ahora van a haber lianas para q el player pueda interactuar
> Cambio de planes

- Assets/Scenes/MatiScene.unity
- Assets/Scripts/Enemy/Attack.cs
- Assets/Scripts/Enemy/Enemy.cs
- Assets/Scripts/Enemy/FollowPlayer.cs
- Assets/Scripts/Enemy/FollowPlayer.cs.meta
cambia de estado entre seguir al player y atacarlo
> cambio de estado y golpe del enemigo

- Assets/Scenes/ChinoScene.unity
- Assets/Scenes/MainScene.unity
- Assets/Scenes/MainScene.unity.meta
- Assets/Scripts/Grappeable.cs
- Assets/Scripts/Impulse.cs
- Assets/Scripts/Impulse.cs.meta
- Assets/Scripts/Interface/IObserverGraspp.cs
- Assets/Scripts/Players/Monkey/ControllerMonkey.cs
- Assets/Scripts/Players/Monkey/ModelMonkey.cs
- Assets/Scripts/Swing.cs
- Assets/Scripts/Swing.cs.meta
- ProjectSettings/EditorBuildSettings.asset
Juntamos las escenas para hacer la build. PD: Hay q arreglar cosas
> Unidad de Escenas

- Assets/Scenes/MatiScene.unity
- Assets/Scripts/Camera/CameraSwitch.cs
- Assets/Scripts/Enemy/Enemy.cs
- Assets/Scripts/Players/Monkey/ModelMonkey.cs
el personaje no se puede mover para adelante cuando pasa a camara2D
> Movimiento2D

- Assets/00_Prefabs/Scenes/LevelPrototype.unity
- Assets/03_Scripts/Managers/GameManager.cs
Las animaciones se ejecutan cuando se pausa todo
> Ajuste de animaciones

- Assets/00_Scenes/LvlProtipo.unity
- Assets/01_Prefabs/Bullet.prefab
- ProjectSettings/EditorBuildSettings.asset
> Ajustar player

- Assets/00_Scenes/ChinoScene.unity
- Assets/03_Scripts/Players/Monkey/ModelMonkey.cs
falta programas cuando se quiera saltar en direccion hacia arriba
> Saltos en las enredaderas

- Assets/01_Prefabs/Global/PLAYER.prefab
- Assets/03_Scripts/Players/Shadow.cs
> Problema de la sombra

- Assets/00_Scenes/ChinoScene.unity
- Assets/01_Prefabs/Global/PLAYER.prefab
- Assets/03_Scripts/Objetos.meta
- Assets/03_Scripts/Objetos/Laser.cs
- Assets/03_Scripts/Objetos/Laser.cs.meta
- ProjectSettings/TagManager.asset
Esta programada la advertencia del rayo laser, antes de que dispare
> Base rayo laser

- Assets/03_Scripts/Players/Banana/ModelBanana.cs
> Salto de la banana

- Assets/03_Scripts/Interacts/Plataform.cs
la plataforma se mueve en el eje z, falta hacer que cuando cambio de personaje la plataforma deje de ser hijo de la banana y que cuando el mono se sube a la plataforma esta lo lleve
> ya se mueve la plataforma(falta pulir)

- Assets/00_Scenes/ChinoScene.unity
- Assets/01_Prefabs/Global/BANANA.prefab
- Assets/03_Scripts/Managers/GameManager.cs
- Assets/03_Scripts/Players/Banana/BananaGuide.cs
- Assets/03_Scripts/Players/Banana/ModelBanana.cs
- Assets/03_Scripts/Players/Monkey/ModelMonkey.cs
Puli unas cosas del ataque cargado, como el radio de la explosion y un tiempo
> Cambios ataque cargado

- Assets/00_Scenes/ChinoScene.unity
- Assets/01_Prefabs/Global/PLAYER.prefab
- Assets/03_Scripts/Camera/CameraTracker.cs
- Assets/03_Scripts/Enemy/Enemy.cs
- Assets/03_Scripts/Interacts/Plataform.cs
- Assets/03_Scripts/Interface/Characters.cs
- Assets/03_Scripts/Interface/Entity.cs
- Assets/03_Scripts/Managers/GameManager.cs
- Assets/03_Scripts/Memento/MementoState.cs
- Assets/03_Scripts/Memento/Rewind.cs
- Assets/03_Scripts/MinigunBar.cs
- Assets/03_Scripts/Players/Banana/BananaGuide.cs
- Assets/03_Scripts/Players/Banana/ControllerBanana.cs
- Assets/03_Scripts/Players/Banana/ModelBanana.cs
- Assets/03_Scripts/Players/Monkey/ControllerMonkey.cs
- Assets/03_Scripts/Players/Monkey/ModelMonkey.cs
- Assets/03_Scripts/Players/Shadow.cs
> Orden del código del player

- Assets/00_Scenes/ChinoScene.unity
- Assets/03_Scripts/Camera/CameraTracker.cs
- Assets/03_Scripts/Interface/Characters.cs
- Assets/03_Scripts/Players/Banana/ModelBanana.cs
- Assets/03_Scripts/Players/Bongo.meta
- Assets/03_Scripts/Players/Bongo/ControllerBongo.cs
- Assets/03_Scripts/Players/Bongo/ControllerBongo.cs.meta
- Assets/03_Scripts/Players/Bongo/ModelBongo.cs
- Assets/03_Scripts/Players/Bongo/ModelBongo.cs.meta
- Assets/03_Scripts/Players/Bongo/ViewBongo.cs
- Assets/03_Scripts/Players/Bongo/ViewBongo.cs.meta
- Assets/03_Scripts/Players/Frank.meta
- Assets/03_Scripts/Players/Frank/ControllerFrank.cs
- Assets/03_Scripts/Players/Frank/ControllerFrank.cs.meta
- Assets/03_Scripts/Players/Frank/ModelFrank.cs
- Assets/03_Scripts/Players/Frank/ModelFrank.cs.meta
- Assets/03_Scripts/Players/Frank/ViewFrank.cs
- Assets/03_Scripts/Players/Frank/ViewFrank.cs.meta
- Assets/03_Scripts/Players/Monkey/ModelMonkey.cs
- Assets/03_Scripts/Players/Shadow.cs
Falta arreglar cosas de la cámara
> Ya estan separados los códigos para los PJ

- Assets/01_Prefabs/Props/Armario (1) Variant.prefab
- Assets/01_Prefabs/Props/Armario (2) Variant.prefab
- Assets/01_Prefabs/Props/Armario Variant.prefab
- Assets/01_Prefabs/Props/Escudo Variant.prefab
- Assets/01_Prefabs/Props/Escudo.prefab
- Assets/01_Prefabs/Props/Espada Variant.prefab
- Assets/01_Prefabs/Props/Libro_Texturas (18) Variant.prefab
- Assets/01_Prefabs/Props/chimenea (2) Variant.prefab
saque las paredes con huecos de frente porque spoileaban el nivel
> arregle colliders en el nivel 1 y cambie algunas paredes

- Assets/03_Scripts/Memento/CheckPoint.cs
- Assets/03_Scripts/Players/Characters.cs
This reverts commit 275df55b3e125e8807ca7ecaa6e90c6a1808d9a4.
> Revert "Cambios de checkpoints lvl 2"

- Assets/03_Scripts/Memento/CheckPoint.cs
- Assets/03_Scripts/Players/Characters.cs
> Chino branch002

- Assets/03_Scripts/AsyncLoad.cs
- Assets/03_Scripts/LoadSceneCollider.cs
- Assets/03_Scripts/LoadSceneCollider.cs.meta
- Assets/03_Scripts/Managers/MenuManager.cs
arregle lo de que se veia verde en el nivel 1
> arregle lo visual del nivel 1 y empece con la union de los niveles

- Assets/00_Scenes/3_ThirdLevel.unity
- Assets/01_Prefabs/Enredaderas/Global/DualDoor_Prefab.prefab
- Assets/03_Scripts/Camera/CameraTracker.cs
- Assets/03_Scripts/Camera/CameraTransparency.cs
- Assets/03_Scripts/Colectionable.cs
- Assets/03_Scripts/Managers/DirectionalLightManager.cs
- Assets/03_Scripts/Managers/DirectionalLightManager.cs.meta
- Assets/03_Scripts/Objetos/ActiveTorch.cs
- Assets/03_Scripts/Objetos/DualDoor.cs
- Assets/03_Scripts/Objetos/TransparencyMaterial.cs
> Comienzo transparencia lvl 3

- Assets/02_Art/1_Animations/Objects/IceBreaking/2_WarningBreaking.anim
- Assets/02_Art/1_Animations/Objects/IceBreaking/3_Break.anim
- Assets/02_Art/1_Animations/Objects/IceBreaking/IceBreaking.controller
- Assets/03_Scripts/Objetos/Platforms/breakablePlatform.cs
> Plataforma rompible arreglada

- Assets/00_Scenes/0_MainMenuBook.unity
> Cambios del menu

- Assets/00_Scenes/3_ThirdLevel.unity
> Min arreglos lvl 3

- Assets/00_Scenes/3_ThirdLevel.unity
- Assets/01_Prefabs/Enredaderas/Global/Platforms/BreakablePlatform.prefab
> Cambios lvl 3

- Assets/03_Scripts/Interacts/Geiser.cs
- Assets/03_Scripts/ObjectPool/ObjectPool.cs
> Geiser modificado

- Assets/00_Scenes/3_ThirdLevel.unity
- Assets/03_Scripts/Interacts/Geiser.cs
- Assets/03_Scripts/Interacts/SuckingHole.cs
sus escalas iniciales y un error de resta en el codigo
> Cambios en los geiseres

- Assets/00_Scenes/0_MainMenuBook.unity
- Assets/01_Prefabs/Canvas/Menu/ButtonSelectorLevel.prefab
Ajuste de collider plataforma giratoria
> Mini cambios en lvl 2 y menu

- Assets/00_Scenes/3_ThirdLevel.unity
> Mini cambios en escen lvl 3

- Assets/01_Prefabs/Objects/Panel.prefab
- Assets/01_Prefabs/Objects/Panel.prefab.meta
- Assets/01_Prefabs/Objects/Piston.prefab
- Assets/01_Prefabs/Players/BONGO.prefab
- Assets/03_Scripts/00_Managers/BoxsManager.cs
- Assets/03_Scripts/00_Managers/BoxsManager.cs.meta
- Assets/03_Scripts/06_Objects/Interacts/Panel.cs
- Assets/03_Scripts/06_Objects/Piston.cs
Falta el ObjectPool de las cajas
> Pistones mas pulidos. Cambio de caámra. Feedback Panel

- Assets/01_Prefabs/Objects/Box/Box.prefab
- Assets/01_Prefabs/Objects/Tape.prefab
- Assets/01_Prefabs/Players/BONGO.prefab
- Assets/01_Prefabs/Players/FRANK.prefab
- Assets/03_Scripts/04_Entitys/Players/Characters.cs
- Assets/03_Scripts/06_Objects/ConveyorBelt.cs
- Assets/03_Scripts/07_PatronesDeDiseño/ObjectPool/Boxes/Box.cs
- Assets/03_Scripts/07_PatronesDeDiseño/ObjectPool/Boxes/SpawnBoxes.cs
- ProjectSettings/TagManager.asset
Me falta una cinta y pulirlo un poco más
> ObjectPool en las cintas

- Assets/00_Scenes/0_MainMenuBook.unity
- Assets/01_Prefabs/Canvas/Menu/ButtonSelectorLevel.prefab
- Assets/03_Scripts/00_Managers/MenuManager.cs
- Assets/03_Scripts/00_Managers/UnlockNextLevel.cs
- Assets/03_Scripts/00_Managers/WinCollider.cs
- Assets/03_Scripts/01_Saves/Json/JsonSaves.cs
- Assets/03_Scripts/01_Saves/Json/LevelData.cs
- Assets/03_Scripts/01_Saves/Json/SaveData.cs
- Assets/03_Scripts/03_Menu/ButtonSelector.cs
- Ahora cuando ya pasaste el nivel, te sale un cartel diciendote si queres jugar con el cronometro o no.
> Mejora del cronometro en el menu principal.

- Assets/01_Prefabs/Objects/Coin.prefab
- Assets/03_Scripts/00_Managers/WinCollider.cs
- Assets/03_Scripts/01_Saves/Json/JsonSaves.cs
- Assets/03_Scripts/01_Saves/Json/LevelData.cs
- Assets/03_Scripts/03_Menu/ButtonSelector.cs
- Assets/03_Scripts/05_View/UI/CoinsUI.cs
- Assets/03_Scripts/06_Objects/Interacts/CoinsCollectibles.cs
- Falta poner tabla de puntuación con el cronómetro.
- Mostar en la interfaz del menú cuantas monedas tienen en total el nivel.
> Las tres estrellas ANDAN!

- Assets/01_Prefabs/Managers/--- RAIL CAMERA ---.prefab
> Cambios en lvl 1. Diseño de nivel

- Assets/03_Scripts/04_Entitys/Players/Bongo/ModelBongo.cs
- Assets/03_Scripts/04_Entitys/Players/Characters.cs
- Assets/03_Scripts/04_Entitys/Players/Frank/ModelFrank.cs
los personajes no se pueden mover hasta que terminan las cinematicas
> mejoras en nivel 2 y arreglo de cinematicas

- Assets/00_Scenes/1_ZoneColl.unity
- Assets/01_Prefabs/Managers/--- RAIL CAMERA ---.prefab
- Assets/03_Scripts/05_View/Camera/Camera Rail/CameraRails.cs
- Assets/03_Scripts/05_View/Camera/CameraSwitch.cs
- Assets/03_Scripts/05_View/Camera/CameraSwitch.cs.meta
- Assets/03_Scripts/05_View/Camera/CameraSwitchEditor.cs
- Assets/03_Scripts/05_View/Camera/CameraSwitchEditor.cs.meta
- Assets/03_Scripts/05_View/Camera/OldCameraSwitch.cs
- Assets/03_Scripts/05_View/Camera/OldCameraSwitch.cs.meta
Todavia me falta pulir detalles
> Seteo de movimiento de cámara zona coleccionalbes lvl 1.

- Assets/00_Scenes/1_ZoneColl.unity
- Assets/03_Scripts/05_View/Camera/Camera Rail/CameraRails.cs
- Assets/03_Scripts/05_View/Camera/CameraSwitch.cs
- Assets/03_Scripts/05_View/Camera/CameraSwitchEditor.cs
- Assets/03_Scripts/05_View/Camera/ChangeTheCameraRail.cs
Aún hay q mejorar la cámara y su movimiento
> Cámara lvl 1 para el final de 10_03

- Assets/01_Prefabs/Managers/--- PauseManager ---.prefab
- Assets/01_Prefabs/Objects/NormalPressurePlate.prefab
- Assets/03_Scripts/00_Managers/CamerasManager.cs
- Assets/03_Scripts/05_View/Camera/FixativeObjectUI.cs
- Assets/03_Scripts/05_View/UI/UICollectible.cs
Falta programar que se actualice los valores que se muestran.
> Interfaz de Pausa agregado.

- Assets/00_Scenes/1_ZoneColl.unity
- Assets/00_Scenes/3_ThirdLevel.unity
- Assets/01_Prefabs/Props/1_Medieval/Rejas.prefab
- Assets/02_Art/1_Animations/Characters/Frank/Menu/Frank_Menu.controller
- Assets/02_Art/1_Animations/Characters/Penguin/AC_Penguin.controller
- Assets/02_Art/1_Animations/Characters/Penguin/Walk.anim
- Assets/03_Scripts/06_Entitys/PenguinFly.cs
- Assets/03_Scripts/BarsWall.cs
memento rejas, camina el pinguino, acomode coleccionable lvl1
> arreglos generales

- Assets/00_Scenes/ChinoScene.unity
- Assets/03_Scripts/05_View/Camera/Camera Rail/CameraRails.cs
- Assets/03_Scripts/05_View/Camera/Camera Rail/NodesOfTheRail.cs
- Assets/03_Scripts/05_View/Camera/Camera Rail/Rail.cs
- Assets/03_Scripts/Editor/NodesOfTheRailEditor.cs
- Assets/03_Scripts/Editor/NodesOfTheRailEditor.cs.meta
No es definitivo, pero funciona para lo que necesitamos ahora.
> Nodos que rotan la cámara.

- Assets/01_Prefabs/Managers/--- RAIL CAMERA ---.prefab
- Assets/03_Scripts/05_View/Camera/Camera Rail/CameraRails.cs
- Assets/03_Scripts/05_View/Camera/Camera Rail/NodesOfTheRail.cs
- Assets/03_Scripts/07_Objects/WallHolograph.cs
- Assets/03_Scripts/Editor/NodesOfTheRailEditor.cs
- Assets/03_Scripts/Editor/UICollectibleEdito.cs
No es definitivo como funcionan ahora los nodos, pero por el momento lo dejo así. Hay q arreglar los niveles (Ejemplo las antorchas)
> Nodo para rotas la cámara y modificar su offset. Final lvl 1 arreglado.

- Assets/03_Scripts/00_Managers/GameManager.cs
- Assets/03_Scripts/00_Managers/WinCollider.cs
- Assets/03_Scripts/01_Saves/Json/LevelData.cs
- Assets/03_Scripts/07_Objects/Interacts/CoinsCollectibles.cs
Si agarro monedas y salgo del nivel, no se van a guardar; tengo q acabar todo el nivel. (Pulir de nuevo el menu de pausa y hacer lo mismo con los coleccioanbles)
> Monedas cuando salgo del nivel.

- Assets/00_Scenes/0_MainMenuBook.unity
- Assets/01_Prefabs/Managers/Canvas/Menu/ButtonSelectorLevel.prefab
- Assets/03_Scripts/04_Menu/ButtonLevelSelector.cs
Ahora se activan si los agarraste.
> Arreglo Imagen coleccionables en el Menu principal.

- Assets/03_Scripts/05_View/Camera/OldCameraSwitch.cs
- Assets/03_Scripts/07_Objects/ActiveTorch.cs
- El bug que sucedia cuando las antorchas no estaban activadas y se veian las particulas.
> Particulas de antorchas desactivadas.

- Assets/01_Prefabs/Managers/--- GameManager ---.prefab
- Assets/01_Prefabs/Managers/Canvas/--- CanvasInGame ---.prefab
- Assets/03_Scripts/00_Managers/GameManager.cs
- Assets/03_Scripts/00_Managers/WinCollider.cs
- Assets/03_Scripts/01_Saves/Json/LevelData.cs
- Assets/03_Scripts/Chronometer.cs
- Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Hice una mini animacion para que el cronometro te avise si perdiste o no la estrella. Una para cuando va el 75% del tiempo y otra para cuando ya se paso el tiempo.
Tambien agregue un mejor tiempo en el lvl 2. Ya se puede jugar en modo cronometro.
> Cronometro Warning.

- Assets/02_Art/10_Cinematic/Nivel-1/B-Cinematic FinishTimeline.playable
- Assets/02_Art/10_Cinematic/Nivel-1/B-Cinematic StartTimeline.playable
- Assets/02_Art/10_Cinematic/win.signal
- Assets/02_Art/10_Cinematic/win.signal.meta
- Assets/03_Scripts/00_Managers/WinCollider.cs
- Dsp de la animación ya sale el canvas de victoria.
> Comienzo final cinematica lvl 1. (Falta pulir aún)

- Assets/03_Scripts/01_Saves/Json/LevelData.cs
- Assets/03_Scripts/05_View/UI/RecordBestTimesView.cs
- Ya no se sumarian milisegundos al record, en teoría.
> (En toeria) Correción de bug "Mejores tiempos".

- Assets/01_Prefabs/Managers/--- RAIL CAMERA ---.prefab
- Assets/03_Scripts/06_Entitys/Players/Bongo/ModelBongo.cs
Tanto en nodos como en colliders
> Cambios en lvl 1 y un poco del lvl 2.

- Assets/01_Prefabs/Managers/--- PauseManager ---.prefab
- Assets/01_Prefabs/Managers/Canvas/--- CanvasInGame ---.prefab
- Assets/03_Scripts/00_Managers/PauseManager.cs
- Assets/03_Scripts/05_View/UI/CanvasWin.cs
- Assets/03_Scripts/05_View/UI/CanvasWin.cs.meta
- Assets/03_Scripts/05_View/UI/UICollectible.cs
Falta animar que se sumen cuantas "monedas" agarro y que tenga una animación.
> Animacion de win canvas (PROTOTIPO)

- Assets/01_Prefabs/Managers/--- PauseManager ---.prefab
- Assets/01_Prefabs/Managers/Canvas/--- CanvasInGame ---.prefab
- Assets/03_Scripts/05_View/UI/CanvasWin.cs
- Assets/03_Scripts/05_View/UI/UICoins.cs
Ahora las monedas se suman progresivamente cuando aparece la pantalla de victoria.
> Suma de monedas en el canvas Win.

- Assets/01_Prefabs/Managers/Canvas/--- CanvasInGame ---.prefab
- Assets/03_Scripts/05_View/Camera/Camera Rail/CameraRails.cs
Mejora en el cambio de cámara al principio del lvl.
> Cambio de cámara en el nivel 2.

- Assets/00_Scenes/NIVELES VIEJOS/4_OldFourthLevel.unity
- Assets/03_Scripts/00_Managers/GameManager.cs
- Assets/03_Scripts/07_Objects/Collectible.cs
- No se actualizaba la interfaz
> Bug de Interfaz coleccionable resuelto

- Assets/00_Scenes/0_MainMenuBook.unity
> Carga zona 1 en lvl 2

- Assets/00_Scenes/3_ThirdLevel/3_ThirdLevel.unity
- Assets/01_Prefabs/Colliders.meta
- Assets/01_Prefabs/Colliders/SpawnPlayerCollider.prefab
- Assets/01_Prefabs/Colliders/SpawnPlayerCollider.prefab.meta
- Assets/03_Scripts/ColliderSpawnPlayer.cs
sigo subiendo cambios por culpa del molesto del chino
> arregle collider de spawn en coleccionable lvl 1

- Assets/00_Scenes/0_Menu/0_MainMenuBook.unity
- Assets/03_Scripts/00_Managers/PauseManager.cs
Al volver la menu desde el Win Canvas
Arreglo de monedas totales lvl 1 (UI Boton)
> Mini arreglos.

- Assets/00_Scenes/3_ThirdLevel/Zones/3 - Zone 03.unity
- Assets/03_Scripts/05_View/Camera/Camera Rail/CameraRails.cs
- Assets/03_Scripts/05_View/Camera/CameraSwitch.cs
- Assets/03_Scripts/05_View/Camera/ChangeTheCameraRail.cs
> Arreglo cámara coleccioanble lvl 1. Arreglo particula Geiser

- Assets/01_Prefabs/Managers/Canvas/--- CanvasInGame ---.prefab
- Estaba el canvas desactivado en el lvl 3 y por eso se trababa.
> Canvas Win lvl 3.
